<?php

namespace App\Filament\Marketing\Resources\TravelAgencies\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class TravelAgencyInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('status')
                    ->placeholder('-'),
                TextEntry::make('fechaIngreso')
                    ->placeholder('-'),
                TextEntry::make('representante')
                    ->placeholder('-'),
                TextEntry::make('idRepresentante')
                    ->placeholder('-'),
                TextEntry::make('FechaNacimientoRepresentante')
                    ->placeholder('-'),
                TextEntry::make('name')
                    ->placeholder('-'),
                TextEntry::make('typeIdentification')
                    ->placeholder('-'),
                TextEntry::make('numberIdentification')
                    ->placeholder('-'),
                TextEntry::make('userPortalWeb')
                    ->placeholder('-'),
                TextEntry::make('aniversary')
                    ->placeholder('-'),
                TextEntry::make('country')
                    ->placeholder('-'),
                TextEntry::make('state')
                    ->placeholder('-'),
                TextEntry::make('city')
                    ->placeholder('-'),
                TextEntry::make('address')
                    ->placeholder('-'),
                TextEntry::make('phone')
                    ->placeholder('-'),
                TextEntry::make('phoneAdditional')
                    ->placeholder('-'),
                TextEntry::make('email')
                    ->label('Email address')
                    ->placeholder('-'),
                TextEntry::make('userInstagram')
                    ->placeholder('-'),
                TextEntry::make('classification')
                    ->placeholder('-'),
                TextEntry::make('comision')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('montoCreditoAprobado')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('nivel')
                    ->placeholder('-'),
                TextEntry::make('agenteSuperiorNivel3')
                    ->placeholder('-'),
                TextEntry::make('agenciaSuperiorNivel2')
                    ->placeholder('-'),
                TextEntry::make('agenciaPpalNivel1')
                    ->placeholder('-'),
                TextEntry::make('createdBy')
                    ->placeholder('-'),
                TextEntry::make('updatedBy')
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('logo')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('nameSecundario')
                    ->placeholder('-'),
                TextEntry::make('emailSecundario')
                    ->placeholder('-'),
                TextEntry::make('phoneSecundario')
                    ->placeholder('-'),
                TextEntry::make('fechaNacimientoSecundario')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_name')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_rif')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_number')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_bank')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_type')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_phone_pm')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_name')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_ci_rif')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_account_number')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_account_bank')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_account_type')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_route')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_zelle')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_ach')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_swift')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_aba')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_address')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_number_mon_inter')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_bank_mon_inter')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_type_mon_inter')
                    ->placeholder('-'),
            ]);
    }
}
