<?php

namespace App\Filament\Business\Resources\Affiliations\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class AffiliationInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('individual_quote_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('owner_code')
                    ->placeholder('-'),
                TextEntry::make('code'),
                TextEntry::make('code_agency'),
                TextEntry::make('agent_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('plan_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('coverage_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('payment_frequency')
                    ->placeholder('-'),
                TextEntry::make('code_individual_quote')
                    ->placeholder('-'),
                TextEntry::make('full_name_payer')
                    ->placeholder('-'),
                TextEntry::make('nro_identificacion_payer')
                    ->placeholder('-'),
                TextEntry::make('phone_payer')
                    ->placeholder('-'),
                TextEntry::make('email_payer')
                    ->placeholder('-'),
                TextEntry::make('relationship_payer')
                    ->placeholder('-'),
                TextEntry::make('full_name_ti')
                    ->placeholder('-'),
                TextEntry::make('nro_identificacion_ti')
                    ->placeholder('-'),
                TextEntry::make('sex_ti')
                    ->placeholder('-'),
                TextEntry::make('birth_date_ti')
                    ->placeholder('-'),
                TextEntry::make('adress_ti')
                    ->placeholder('-'),
                TextEntry::make('city_id_ti')
                    ->placeholder('-'),
                TextEntry::make('state_id_ti')
                    ->placeholder('-'),
                TextEntry::make('country_id_ti')
                    ->placeholder('-'),
                TextEntry::make('region_ti')
                    ->placeholder('-'),
                TextEntry::make('phone_ti')
                    ->placeholder('-'),
                TextEntry::make('email_ti')
                    ->placeholder('-'),
                IconEntry::make('cuestion_1')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_2')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_3')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_4')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_5')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_6')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_7')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_8')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_9')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_10')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_11')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_12')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_13')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_14')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_15')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('cuestion_16')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('observations_cuestions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('full_name_agent')
                    ->placeholder('-'),
                TextEntry::make('code_agent')
                    ->placeholder('-'),
                TextEntry::make('date_today')
                    ->placeholder('-'),
                TextEntry::make('created_by')
                    ->placeholder('-'),
                TextEntry::make('status'),
                TextEntry::make('document')
                    ->placeholder('-'),
                TextEntry::make('activated_at')
                    ->placeholder('-'),
                TextEntry::make('family_members')
                    ->placeholder('-'),
                TextEntry::make('vaucher_ils')
                    ->placeholder('-'),
                TextEntry::make('date_payment_initial_ils')
                    ->placeholder('-'),
                TextEntry::make('date_payment_final_ils')
                    ->placeholder('-'),
                TextEntry::make('document_ils')
                    ->placeholder('-'),
                TextEntry::make('observations_payment')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('fee_anual')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('total_amount')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('signature_agent')
                    ->placeholder('-'),
                TextEntry::make('upload_documents')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('signature_ti')
                    ->placeholder('-'),
                TextEntry::make('observations')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('owner_agent')
                    ->placeholder('-'),
                TextEntry::make('activation_date')
                    ->placeholder('-'),
                IconEntry::make('feedback')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('feedback_dos')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('age')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
