<?php

namespace App\Filament\Administration\Resources\TdevReports\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class TdevReportInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('fecha'),
                TextEntry::make('vaucher'),
                TextEntry::make('agencia')
                    ->placeholder('-'),
                TextEntry::make('agente'),
                TextEntry::make('subagente')
                    ->placeholder('-'),
                TextEntry::make('salida'),
                TextEntry::make('regreso'),
                TextEntry::make('fecha_anulacion'),
                TextEntry::make('pasajero'),
                TextEntry::make('nacionalidad'),
                TextEntry::make('tipo_documento'),
                TextEntry::make('nro_documento'),
                TextEntry::make('categoria_del_plan'),
                TextEntry::make('descripcion_del_plan'),
                TextEntry::make('origen_del_viaje'),
                TextEntry::make('destino')
                    ->placeholder('-'),
                TextEntry::make('nro_dias_de_servicio'),
                TextEntry::make('edad'),
                TextEntry::make('estatus_del_vaucher'),
                TextEntry::make('referencia'),
                TextEntry::make('plan_familiar'),
                TextEntry::make('descuento')
                    ->numeric(),
                TextEntry::make('impuesto')
                    ->numeric(),
                TextEntry::make('precio_upgrade')
                    ->numeric(),
                TextEntry::make('precio_de_venta')
                    ->numeric(),
                TextEntry::make('total_precio_venta')
                    ->numeric(),
                TextEntry::make('fecha_pago_vaucher')
                    ->placeholder('-'),
                TextEntry::make('forma_de_pago')
                    ->placeholder('-'),
                TextEntry::make('entidad_bancaria_receptora')
                    ->placeholder('-'),
                TextEntry::make('referencia_bancaria')
                    ->placeholder('-'),
                TextEntry::make('tasa_pago')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('monto_abonado_en_cuenta')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('estatus_pago')
                    ->placeholder('-'),
                TextEntry::make('dias_emision')
                    ->placeholder('-'),
                TextEntry::make('porcen_comision')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('comision_agencia')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('comision_agente')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('comision_subagente')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('monto_comision')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('estatus_comision')
                    ->placeholder('-'),
                TextEntry::make('fecha_pago_comision')
                    ->placeholder('-'),
                TextEntry::make('referencia_bancaria_comision')
                    ->placeholder('-'),
                TextEntry::make('relacion_comision')
                    ->placeholder('-'),
                TextEntry::make('observaciones')
                    ->placeholder('-'),
                TextEntry::make('neto_del_servicio')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('utilidad_tdev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('status_report')
                    ->placeholder('-'),
            ]);
    }
}
