<?php

namespace App\Filament\Resources\TdevReports\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class TdevReportForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('fecha')
                    ->required(),
                TextInput::make('vaucher')
                    ->required(),
                TextInput::make('agente')
                    ->required(),
                TextInput::make('subagente'),
                TextInput::make('salida')
                    ->required(),
                TextInput::make('regreso')
                    ->required(),
                TextInput::make('fecha_anulacion')
                    ->required(),
                TextInput::make('pasajero')
                    ->required(),
                TextInput::make('nacionalidad')
                    ->required(),
                TextInput::make('tipo_documento')
                    ->required(),
                TextInput::make('nro_documento')
                    ->required(),
                TextInput::make('categoria_del_plan')
                    ->required(),
                TextInput::make('descripcion_del_plan')
                    ->required(),
                TextInput::make('origen_del_viaje')
                    ->required(),
                TextInput::make('nro_dias_de_servicio')
                    ->required(),
                TextInput::make('edad')
                    ->required(),
                TextInput::make('estatus_del_vaucher')
                    ->required(),
                TextInput::make('referencia')
                    ->required(),
                TextInput::make('plan_familiar')
                    ->required(),
                TextInput::make('descuento')
                    ->required()
                    ->numeric(),
                TextInput::make('impuesto')
                    ->required()
                    ->numeric(),
                TextInput::make('precio_upgrade')
                    ->required()
                    ->numeric(),
                TextInput::make('precio_de_venta')
                    ->required()
                    ->numeric(),
                TextInput::make('total_precio_venta')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('fecha_pago_vaucher'),
                TextInput::make('forma_de_pago'),
                TextInput::make('entidad_bancaria_receptora'),
                TextInput::make('referencia_bancaria'),
                TextInput::make('tasa_pago')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('monto_abonado_en_cuenta')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('estatus_pago'),
                TextInput::make('dias_emision'),
                TextInput::make('porcen_comision')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('comision_agencia')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('comision_agente')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('comision_subagente')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('monto_comision')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('estatus_comision'),
                TextInput::make('fecha_pago_comision'),
                TextInput::make('referencia_bancaria_comision'),
                TextInput::make('relacion_comision'),
                TextInput::make('observaciones'),
                TextInput::make('neto_del_servicio')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('utilidad_tdev')
                    ->required()
                    ->numeric()
                    ->default(0.0),
            ]);
    }
}
