<?php

namespace App\Filament\Business\Resources\Agencies\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class AgencyInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('owner_code')
                    ->placeholder('-'),
                TextEntry::make('code')
                    ->placeholder('-'),
                TextEntry::make('agency_type_id'),
                TextEntry::make('rif')
                    ->placeholder('-'),
                TextEntry::make('name_corporative')
                    ->placeholder('-'),
                TextEntry::make('ci_responsable')
                    ->placeholder('-'),
                TextEntry::make('address')
                    ->placeholder('-'),
                TextEntry::make('email')
                    ->label('Email address'),
                TextEntry::make('phone')
                    ->placeholder('-'),
                TextEntry::make('user_instagram')
                    ->placeholder('-'),
                TextEntry::make('country.name')
                    ->label('Country')
                    ->placeholder('-'),
                TextEntry::make('state.id')
                    ->label('State')
                    ->placeholder('-'),
                TextEntry::make('city.id')
                    ->label('City')
                    ->placeholder('-'),
                TextEntry::make('region')
                    ->placeholder('-'),
                TextEntry::make('name_contact_2')
                    ->placeholder('-'),
                TextEntry::make('email_contact_2')
                    ->placeholder('-'),
                TextEntry::make('phone_contact_2')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_name')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_rif')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_number')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_bank')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_account_type')
                    ->placeholder('-'),
                TextEntry::make('local_beneficiary_phone_pm')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_name')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_ci_rif')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_account_number')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_account_bank')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_account_type')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_route')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_zelle')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_ach')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_swift')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_aba')
                    ->placeholder('-'),
                TextEntry::make('extra_beneficiary_address')
                    ->placeholder('-'),
                IconEntry::make('tdec')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('tdev')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('commission_tdec')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('commission_tdec_renewal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('commission_tdev')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('commission_tdev_renewal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('file_acuerdo')
                    ->placeholder('-'),
                TextEntry::make('file_planilla')
                    ->placeholder('-'),
                TextEntry::make('status'),
                TextEntry::make('created_by')
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('fir_dig_agent')
                    ->placeholder('-'),
                TextEntry::make('fir_dig_agency')
                    ->placeholder('-'),
                TextEntry::make('date_register')
                    ->placeholder('-'),
                IconEntry::make('is_accepted_conditions')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('file_ci_rif')
                    ->placeholder('-'),
                TextEntry::make('file_w8_w9')
                    ->placeholder('-'),
                TextEntry::make('file_account_usd')
                    ->placeholder('-'),
                TextEntry::make('file_account_bsd')
                    ->placeholder('-'),
                TextEntry::make('file_account_zelle')
                    ->placeholder('-'),
                TextEntry::make('comments')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('owner_master')
                    ->placeholder('-'),
                TextEntry::make('owner_general')
                    ->placeholder('-'),
                TextEntry::make('owner_agent')
                    ->placeholder('-'),
                TextEntry::make('user_tdev')
                    ->placeholder('-'),
                IconEntry::make('conf_position_menu')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('type_chart')
                    ->placeholder('-'),
                TextEntry::make('ownerAccountManagers')
                    ->numeric()
                    ->placeholder('-'),
            ]);
    }
}
