<?php

namespace App\Filament\Resources\TelemedicineHistoryPatients\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class TelemedicineHistoryPatientInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('telemedicine_patient_id')
                    ->numeric(),
                TextEntry::make('cod_history'),
                TextEntry::make('user_id'),
                TextEntry::make('cod_patient'),
                TextEntry::make('history_date'),
                TextEntry::make('weight'),
                TextEntry::make('height'),
                TextEntry::make('reason'),
                TextEntry::make('current_illness'),
                TextEntry::make('strain'),
                TextEntry::make('temperature'),
                TextEntry::make('breaths'),
                TextEntry::make('pulse'),
                TextEntry::make('saturation'),
                TextEntry::make('condition'),
                IconEntry::make('cancer')
                    ->boolean(),
                IconEntry::make('diabetes')
                    ->boolean(),
                IconEntry::make('tension_alta')
                    ->boolean(),
                IconEntry::make('cardiacos')
                    ->boolean(),
                IconEntry::make('psiquiatricas')
                    ->boolean(),
                IconEntry::make('alteraciones_coagulacion')
                    ->boolean(),
                IconEntry::make('trombosis_embooleanas')
                    ->boolean(),
                IconEntry::make('tranfusiones_sanguineas')
                    ->boolean(),
                IconEntry::make('COVID19')
                    ->boolean(),
                IconEntry::make('hepatitis')
                    ->boolean(),
                IconEntry::make('VIH_SIDA')
                    ->boolean(),
                IconEntry::make('gastritis_ulceras')
                    ->boolean(),
                IconEntry::make('neurologia')
                    ->boolean(),
                IconEntry::make('ansiedad_angustia')
                    ->boolean(),
                IconEntry::make('tiroides')
                    ->boolean(),
                IconEntry::make('lupus')
                    ->boolean(),
                IconEntry::make('enfermedad_autoimmune')
                    ->boolean(),
                IconEntry::make('diabetes_mellitus')
                    ->boolean(),
                IconEntry::make('presion_arterial_alta')
                    ->boolean(),
                IconEntry::make('tiene_cateter_venoso')
                    ->boolean(),
                IconEntry::make('fracturas')
                    ->boolean(),
                IconEntry::make('trombosis_venosa')
                    ->boolean(),
                IconEntry::make('embooleania_pulmonar')
                    ->boolean(),
                IconEntry::make('varices_piernas')
                    ->boolean(),
                IconEntry::make('insuficiencia_arterial')
                    ->boolean(),
                IconEntry::make('coagulacion_anormal')
                    ->boolean(),
                IconEntry::make('moretones_frecuentes')
                    ->boolean(),
                IconEntry::make('sangrado_cirugias_previas')
                    ->boolean(),
                IconEntry::make('sangrado_cepillado_dental')
                    ->boolean(),
                IconEntry::make('alcohol')
                    ->boolean(),
                IconEntry::make('drogas')
                    ->boolean(),
                IconEntry::make('vacunas_recientes')
                    ->boolean(),
                IconEntry::make('transfusiones_sanguineas')
                    ->boolean(),
                TextEntry::make('edad_primera_menstruation'),
                TextEntry::make('fecha_ultima_regla'),
                TextEntry::make('numero_embarazos')
                    ->numeric(),
                TextEntry::make('numero_partos')
                    ->numeric(),
                TextEntry::make('numero_abortos')
                    ->numeric(),
                TextEntry::make('cesareas')
                    ->numeric(),
                TextEntry::make('observations_ginecologica'),
                TextEntry::make('observations_allergies'),
                TextEntry::make('observations_medication'),
                TextEntry::make('observations_back_family'),
                TextEntry::make('observations_diagnosis'),
                TextEntry::make('observations_not_pathological'),
                TextEntry::make('created_by'),
                TextEntry::make('created_at')
                    ->dateTime(),
                TextEntry::make('updated_at')
                    ->dateTime(),
            ]);
    }
}
