<?php

namespace App\Filament\Master\Resources\Commissions\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class CommissionForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('code'),
                TextInput::make('date_payment_affiliate')
                    ->required(),
                TextInput::make('agency_id')
                    ->numeric(),
                TextInput::make('code_agency'),
                TextInput::make('owner_code'),
                TextInput::make('agent_id')
                    ->numeric(),
                TextInput::make('plan_id')
                    ->required()
                    ->numeric(),
                TextInput::make('coverage_id')
                    ->numeric(),
                TextInput::make('sale_id')
                    ->required()
                    ->numeric(),
                TextInput::make('invoice_number')
                    ->required(),
                TextInput::make('affiliate_full_name')
                    ->required(),
                TextInput::make('amount')
                    ->required()
                    ->numeric(),
                TextInput::make('payment_method')
                    ->required(),
                TextInput::make('veto')
                    ->required()
                    ->default('ANUAL'),
                TextInput::make('payment_frequency')
                    ->required(),
                TextInput::make('commission_agency_master')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agency_general')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agent')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('total_payment_commission')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('date_payment_commission')
                    ->required(),
                TextInput::make('created_by')
                    ->required(),
                TextInput::make('commission_agency_master_tdec')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agency_general_tdec')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agent_tdec')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('pay_amount_usd')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('pay_amount_ves')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('payment_method_usd'),
                TextInput::make('payment_method_ves'),
                TextInput::make('commission_agency_master_usd')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agency_general_usd')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agent_usd')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agency_master_ves')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agency_general_ves')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('commission_agent_ves')
                    ->numeric()
                    ->default(0.0),
                TextInput::make('date_ini'),
                TextInput::make('date_end'),
            ]);
    }
}
