<?php

declare(strict_types=1);

namespace App\Support;

final class CierreMesSlides
{
    /**
     * @return list<array{
     *     id: string,
     *     type: string,
     *     title: string,
     *     subtitle: string,
     *     module: string,
     *     icon: string,
     *     color: string,
     *     preview: array{type: string, path?: string, panel?: string, tip?: string},
     *     highlights: list<string>,
     *     tags: list<string>
     * }>
     */
    public static function all(): array
    {
        return [
            [
                'id' => 'intro',
                'type' => 'title',
                'title' => 'Cierre de Mes',
                'subtitle' => 'Un recorrido por todo lo que mejoramos en la plataforma durante junio de 2026.',
                'module' => 'Bienvenida',
                'icon' => '🚀',
                'color' => '#0064a1',
                'preview' => ['type' => 'brand'],
                'highlights' => [
                    'Preparamos más de 15 mejoras en ventas, soporte, marketing y operaciones diarias.',
                    'A la derecha verás la pantalla real del sistema: puedes hacer clic y probarla en vivo.',
                ],
                'tags' => ['Tu Dr. en Casa', 'IntegraCorp'],
            ],
            [
                'id' => 'cotizaciones-pdf',
                'type' => 'feature',
                'title' => 'Propuestas en PDF más claras',
                'subtitle' => 'Ahora las cotizaciones individuales y corporativas se ven igual de ordenadas al imprimirlas o enviarlas.',
                'module' => 'Cotizaciones',
                'icon' => '📄',
                'color' => '#0ea5e9',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/corporate-quotes',
                    'panel' => 'Negocios → Cotizaciones corporativas',
                    'tip' => 'Abre una cotización y descarga el PDF para ver la nueva tabla de coberturas.',
                ],
                'highlights' => [
                    'La tabla de coberturas se ve igual en pantalla y en el PDF.',
                    'Descarga la propuesta corporativa directamente desde el listado.',
                    'Documento más limpio y fácil de leer para el cliente.',
                ],
                'tags' => ['Ventas', 'Documentos'],
            ],
            [
                'id' => 'cotizaciones-formularios',
                'type' => 'feature',
                'title' => 'Crear cotizaciones más fácil',
                'subtitle' => 'Los formularios para armar cotizaciones individuales y corporativas ahora son más simples y parecidos entre sí.',
                'module' => 'Cotizaciones',
                'icon' => '📝',
                'color' => '#0ea5e9',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/corporate-quotes/create',
                    'panel' => 'Negocios → Nueva cotización corporativa',
                    'tip' => 'Recorre el formulario: los pasos están más ordenados y unificados.',
                ],
                'highlights' => [
                    'Menos pasos confusos al crear o revisar una cotización.',
                    'La misma experiencia en planes individuales y corporativos.',
                    'Pantallas de creación y consulta alineadas entre sí.',
                ],
                'tags' => ['Ventas', 'Formularios'],
            ],
            [
                'id' => 'cotizaciones-tablas',
                'type' => 'feature',
                'title' => 'Mejor control de las cotizaciones',
                'subtitle' => 'Listados más útiles y números claros para saber cómo van las ventas.',
                'module' => 'Cotizaciones',
                'icon' => '📊',
                'color' => '#0ea5e9',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/corporate-quote-requests',
                    'panel' => 'Negocios → Solicitudes corporativas',
                    'tip' => 'Revisa los totales arriba y los gráficos por canal y por creador.',
                ],
                'highlights' => [
                    'Las tablas muestran lo más importante de un vistazo.',
                    'Resúmenes con totales de cotizaciones individual y corporativa.',
                    'Descarga listados en Excel desde el botón de exportar.',
                    'Gráficos de solicitudes por canal y por quien las creó.',
                ],
                'tags' => ['Reportes', 'Ventas'],
            ],
            [
                'id' => 'planes',
                'type' => 'feature',
                'title' => 'Planes de salud más fáciles de armar',
                'subtitle' => 'Crear y editar planes médicos es más seguro y con menos errores.',
                'module' => 'Planes',
                'icon' => '🏥',
                'color' => '#10b981',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/plans',
                    'panel' => 'Negocios → Planes',
                    'tip' => 'Entra a crear o editar un plan y nota los campos y validaciones nuevas.',
                ],
                'highlights' => [
                    'Al guardar un plan, la información se valida mejor antes de confirmar.',
                    'Campos útiles que antes faltaban en el formulario.',
                    'Editar un plan existente es más directo y ordenado.',
                ],
                'tags' => ['Productos', 'Salud'],
            ],
            [
                'id' => 'helpdesk-notas',
                'type' => 'feature',
                'title' => 'Soporte: saber qué mensajes faltan por leer',
                'subtitle' => 'El equipo ya no pierde comentarios nuevos en los tickets de ayuda.',
                'module' => 'Soporte',
                'icon' => '💬',
                'color' => '#8b5cf6',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/helpdesks',
                    'panel' => 'Negocios → Helpdesk',
                    'tip' => 'Mira el número en el menú lateral y las marcas en tickets con notas nuevas.',
                ],
                'highlights' => [
                    'Contador cuando hay tickets con respuestas sin leer.',
                    'El aviso se ve en el menú de todos los módulos con soporte.',
                    'Dentro del ticket se marcan las observaciones nuevas.',
                ],
                'tags' => ['Helpdesk', 'Comunicación'],
            ],
            [
                'id' => 'helpdesk-tabla',
                'type' => 'feature',
                'title' => 'Tickets de soporte más organizados',
                'subtitle' => 'La lista de solicitudes de ayuda es más clara en todos los departamentos.',
                'module' => 'Soporte',
                'icon' => '🎫',
                'color' => '#8b5cf6',
                'preview' => [
                    'type' => 'system',
                    'path' => '/operations/helpdesks',
                    'panel' => 'Operaciones → Helpdesk',
                    'tip' => 'La misma tabla mejorada está en Negocios, Marketing y Administración.',
                ],
                'highlights' => [
                    'Misma vista en Negocios, Marketing, Operaciones y Administración.',
                    'Al agregar una observación, el sistema sabe quién ya la leyó.',
                    'Columnas más útiles para dar seguimiento a cada caso.',
                ],
                'tags' => ['Helpdesk', 'Equipos'],
            ],
            [
                'id' => 'agenda-corporativa',
                'type' => 'feature',
                'title' => 'Agenda corporativa por áreas',
                'subtitle' => 'El calendario de actividades ahora se puede filtrar por departamento y ver invitaciones pendientes.',
                'module' => 'Agenda',
                'icon' => '📅',
                'color' => '#f59e0b',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/agenda-corporativa',
                    'panel' => 'Negocios → Agenda corporativa',
                    'tip' => 'Usa los filtros por departamento y abre un día del calendario.',
                ],
                'highlights' => [
                    'Cada actividad se clasifica por área de la empresa.',
                    'Filtros rápidos: Marketing, Operaciones u otro departamento.',
                    'Aviso en el menú cuando hay invitaciones sin responder.',
                    'Vista del día del calendario más clara y cómoda.',
                ],
                'tags' => ['Calendario', 'Coordinación'],
            ],
            [
                'id' => 'notificaciones-masivas',
                'type' => 'feature',
                'title' => 'Envíos masivos programados',
                'subtitle' => 'Los correos y mensajes a muchas personas se pueden planificar y hacer seguimiento.',
                'module' => 'Marketing',
                'icon' => '📢',
                'color' => '#ec4899',
                'preview' => [
                    'type' => 'system',
                    'path' => '/marketing/mass-notifications',
                    'panel' => 'Marketing → Notificaciones masivas',
                    'tip' => 'Abre una campaña para ver el asunto del correo, la programación y el estado de entrega.',
                ],
                'highlights' => [
                    'Programa el envío para una fecha y hora específica.',
                    'Personaliza el asunto del correo por campaña.',
                    'Ve cuántos mensajes se enviaron, llegaron o fallaron.',
                    'Detalle por persona: quién recibió y quién no.',
                ],
                'tags' => ['Correos', 'Campañas'],
            ],
            [
                'id' => 'cumpleanos',
                'type' => 'feature',
                'title' => 'Felicitaciones de cumpleaños',
                'subtitle' => 'Las notificaciones de cumpleaños son más fáciles de configurar y enviar.',
                'module' => 'Marketing',
                'icon' => '🎂',
                'color' => '#ec4899',
                'preview' => [
                    'type' => 'system',
                    'path' => '/marketing/birthday-notifications',
                    'panel' => 'Marketing → Cumpleaños',
                    'tip' => 'Revisa cómo se elige la audiencia y se gestiona cada campaña.',
                ],
                'highlights' => [
                    'Elige con claridad a quién llegará la felicitación.',
                    'Pantallas de creación, edición y listado más ordenadas.',
                    'Mejor control antes de activar una campaña.',
                ],
                'tags' => ['Automatización', 'Clientes'],
            ],
            [
                'id' => 'export-csv',
                'type' => 'feature',
                'title' => 'Descargar datos a Excel',
                'subtitle' => 'Varias listas del módulo de negocios se pueden exportar con un clic.',
                'module' => 'Reportes',
                'icon' => '📥',
                'color' => '#14b8a6',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/agencies',
                    'panel' => 'Negocios → Agencias',
                    'tip' => 'Busca el botón de exportar arriba de la tabla. También está en agentes y citas.',
                ],
                'highlights' => [
                    'Agencias, agentes y citas comerciales listas para descargar.',
                    'Población afiliada corporativa exportable para análisis.',
                    'Listado de cotizaciones corporativas en archivo.',
                    'Botón de descarga visible en cada tabla.',
                ],
                'tags' => ['Excel', 'Datos'],
            ],
            [
                'id' => 'afiliaciones-docs',
                'type' => 'feature',
                'title' => 'Documentos de afiliación',
                'subtitle' => 'Revisar y compartir papeles de afiliación individual y corporativa es más sencillo.',
                'module' => 'Afiliaciones',
                'icon' => '📎',
                'color' => '#14b8a6',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/affiliation-corporates',
                    'panel' => 'Negocios → Afiliaciones corporativas',
                    'tip' => 'Abre una afiliación y prueba la vista previa de documentos.',
                ],
                'highlights' => [
                    'Vista previa de documentos antes de enviarlos.',
                    'Mejor experiencia en afiliaciones individuales y corporativas.',
                    'Acciones nuevas en el listado de afiliaciones corporativas.',
                ],
                'tags' => ['Afiliados', 'Documentos'],
            ],
            [
                'id' => 'tablas-business',
                'type' => 'feature',
                'title' => 'Red comercial más ordenada',
                'subtitle' => 'Agencias, agentes y citas tienen listados más prácticos para el día a día.',
                'module' => 'Negocios',
                'icon' => '🗂️',
                'color' => '#6366f1',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/agents',
                    'panel' => 'Negocios → Agentes',
                    'tip' => 'Compara columnas y acciones con la vista de agencias y citas comerciales.',
                ],
                'highlights' => [
                    'Exportar agencias y agentes para reportes externos.',
                    'Citas comerciales descargables desde la misma pantalla.',
                    'Listado de ciudades simplificado y más fácil de usar.',
                ],
                'tags' => ['Agencias', 'Agentes'],
            ],
            [
                'id' => 'ux-transversal',
                'type' => 'feature',
                'title' => 'Pequeños detalles que suman',
                'subtitle' => 'Ajustes en toda la plataforma para que trabajar sea más cómodo.',
                'module' => 'Plataforma',
                'icon' => '✨',
                'color' => '#0064a1',
                'preview' => [
                    'type' => 'system',
                    'path' => '/business/agenda-corporativa',
                    'panel' => 'Negocios → Agenda corporativa',
                    'tip' => 'Fíjate en los avatares del equipo y los estilos unificados del calendario.',
                ],
                'highlights' => [
                    'Si la sesión expira, aparece un mensaje claro en lugar de un error.',
                    'Avatares del equipo más visibles en calendarios y actividades.',
                    'Colores y estilos más consistentes en soporte y agenda.',
                ],
                'tags' => ['Experiencia', 'Usabilidad'],
            ],
            [
                'id' => 'cierre',
                'type' => 'summary',
                'title' => '¡Gracias por su atención!',
                'subtitle' => 'Seguimos mejorando IntegraCorp para que Tu Dr. en Casa ofrezca el mejor servicio.',
                'module' => 'Cierre',
                'icon' => '🎯',
                'color' => '#0064a1',
                'preview' => ['type' => 'brand'],
                'highlights' => [
                    '15 mejoras en cotizaciones, soporte, agenda, marketing y reportes.',
                    'Cada cambio busca ahorrar tiempo y evitar errores en el día a día.',
                    '¿Preguntas? Podemos profundizar en cualquier pantalla del sistema.',
                ],
                'tags' => ['Junio 2026', 'Tu Dr. en Casa'],
            ],
        ];
    }
}
